# Generated by Django 4.0.6 on 2023-05-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TreeV', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
