# Generated by Django 4.0.6 on 2023-06-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TreeV', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
