# Generated by Django 4.0.6 on 2023-06-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TreeV', '0004_rename_user_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cid',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
